steps:
# Access the id_github file from Secret Manager
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=secret-name > /root/.ssh/id_github' ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set up git with key and domain
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_github
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_github
    EOF
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Connect to the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:pila-project/karelPrototype.git
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Install npm packages
- name: node
  entrypoint: npm
  args: ["install"]

# Build and create .env file
- name: node
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'REACT_APP_apiKey=${_APIKEY}'
    - 'REACT_APP_authDomain=${_AUTHDOMAIN}'
    - 'REACT_APP_databaseURL=${_DATABASEURL}'
    - 'REACT_APP_projectId=${_PROJECTID}'
    - 'REACT_APP_storageBucket=${_STORAGEBUCKET}'
    - 'REACT_APP_messagingSenderId=${_MESSAGINGSENDERID}'
    - 'REACT_APP_appId=${_APPID}'

- name: ubuntu
  args: ['cat','.env']

# Build the files
- name: node
  entrypoint: npm
  args: ['run', 'build']

# Deploy on google cloud
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
