export const UPDATE_STATUS = "UPDATE_STATUS";
export const UPDATE_CODE = "UPDATE_CODE";
export const UPDATE_CURRENT_VIEW = "UPDATE_CURRENT_VIEW";
export const PROBLEM_COMPLETE = "PROBLEM_COMPLETE";
export const PRE_ITEM_COMPLETE = "PRE_ITEM_COMPLETE";