// export {default} from './DemoList'
export {default as DemoMultipleTests} from './DemoMultipleTests'
export {default as DemoMultipleTests2} from './DemoMultipleTests2'
export {default as DemoMultipleTests3_CustomStarterCode} from './DemoMultipleTests3_CustomStarterCode'
export {default as DemoMultipleTests3} from './DemoMultipleTests3'
export {default as DemoPrePostIde} from './DemoPrePostIde'
export {default as KarelCommands} from './KarelCommands'
export {default as KarelCommandsMove} from './KarelCommandsMove'
export {default as KarelCommandsPickStone} from './KarelCommandsPickStone'
export {default as KarelCommandsPlaceStone} from './KarelCommandsPlaceStone'
export {default as KarelCommandsTurnLeft} from './KarelCommandsTurnLeft'
export {default as Learning} from './Learning'
export {default as Motivation} from './Motivation'
export {default as PostTest} from './PostTest'
export {default as PreTest} from './PreTest'